[package]
name = "torrust-index-backend"
version = "2.0.0-dev.1"
authors = ["Mick van Dijke <mick@dutchbits.nl>", "Wesley Bijleveld <wesley@dutchbits.nl>"]
edition = "2021"
default-run = "main"

[profile.dev.package.sqlx-macros]
opt-level = 3

[dependencies]
actix-web = "4.3"
actix-multipart = "0.6"
actix-cors = "0.6"
async-trait = "0.1"
futures = "0.3"
sqlx = { version = "0.6", features = [ "runtime-tokio-native-tls", "sqlite", "mysql", "migrate", "time" ] }
config = "0.13"
toml = "0.7"
derive_more = "0.99"
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1"
serde_json = "1.0"
serde_bencode = "0.2.3"
serde_bytes = "0.11"
urlencoding = "2.1"
argon2 = "0.5"
rand_core = { version = "0.6", features = ["std"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
jsonwebtoken = "8.3"
sha-1 = "0.10"
reqwest = { version = "0.11", features = [ "json", "multipart" ] }
tokio = {version = "1.28", features = ["macros", "io-util", "net", "time", "rt-multi-thread", "fs", "sync", "signal"]}
lettre = { version = "0.10", features = ["builder", "tokio1", "tokio1-rustls-tls", "tokio1-native-tls", "smtp-transport"]}
sailfish = "0.6"
regex = "1.8"
pbkdf2 = { version = "0.12", features = ["simple"] }
text-colorizer = "1.0.0"
log = "0.4"
fern = "0.6"
bytes = "1.4"
text-to-png = "0.2"
indexmap = "1.9"

[dev-dependencies]
rand = "0.8"
tempfile = "3.5"
uuid = { version = "1.3", features = [ "v4"] }
which = "4.4"
